/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <LCDHAL.h>
#include <DEM128064E1FGH.h>
#include <stdint.h>
#include "stm32f407xx.h"
#include "stm32f407xx_gpio.h"
#include "stm32f407xx_spi.h"
#include "Stm32f407xx_RCC.h"
#include "Stm32f407xx_tim.h"
#include "keybrd.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClockConfig(void);
void Error_handler(void);
void TIM6_Load(void);

int main(void)
{
	SystemClockConfig();
	TIM6_Load();
	keybrdMatrixInit();
	LCD_Init();

	//SPI2->CR[0] |= (1<<6);
	//LCD_Config();


	//LCD_Rst();


while(1){

		LCD_Bias();
		LCD_ADC(ENABLE);
		LCD_ComMode();
		//LCD_StrtLineAddr(0x40);
		LCD_RbRa();
		delay(TIM6, 5);
		LCD_Evol();
		LCD_PwrConfig();
		LCD_BstMult();
		delay(TIM6, 5);
		LCD_Onoff(ENABLE);
		LCD_Normal(DISABLE);

		LCD_DisplayAllPnts(ENABLE);


	}



}
void SystemClockConfig(void)
{
	//RCC
		RCC_Handle_t RCChandle;
		RCChandle.pRCC =RCC;
		RCChandle.CLK_Config.CLKsrc = HSI;

		//HSI = 16Mhz. M=8 , N=100, P=8.
		//FVCO = F*N/M=16*100/8=200MHz, sysclk = Fvco/p = 25MHz.
		RCChandle.CLK_Config.MPLL[0]=8;
		RCChandle.CLK_Config.MPLL[1]=100;
		RCChandle.CLK_Config.MPLL[2]=0b11;//0b11 = divide by 8, binary doesn't equal decimal here.
		RCChandle.CLK_Config.MPLL[3]=0;
		RCChandle.CLK_Config.MPLL[4]=4;
		RCChandle.CLK_Config.MPLL[5]=1;

		//AHB -> 25MHz
		RCChandle.CLK_Config.HPRE = 0;

		//APB1-> 25MHz
		RCChandle.CLK_Config.PPRE1 = 0;
		//APB2-> 25MHz
		RCChandle.CLK_Config.PPRE2 = 0;


		RCC_Init(&RCChandle);
}

void TIM6_Load(void)
{
	TIM_Handel_t TIM6_H;
	TIM6_H.pTIMX =TIM6;
	TIM6_H.TimxTB.Prescaler =15900;//timer clock = 25M/25000=1khz
	TIM_init(&TIM6_H);

}
